name: ekko_cli
description: CLI For EKKO Boilerplate
version: 0.4.0+1

repository: https://github.com/Katekko/cli_ekko

environment:
  sdk: ">=2.15.0 <3.0.0"

executables: 
  ekko:
  
dependencies:
  ansicolor: ^2.0.1
  recase: ^4.0.0
  meta: ^1.7.0
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.1
